### ISSUE TITLE
对接第三方接口使用JWT作为token发送会被HttpSender里面的URL.encode()转义造成token无效问题

### ISSUE THREAD

**Issue by HK-hub** [burukeYou/UniAPI#1]
对接第三方接口使用JWT作为token发送会被HttpSender里面的URL.encode()转义造成token无效问题
com.burukeyou.uniapi.http.core.channel.DefaultHttpApiInvoker#sendHttpRequest
```java
Map<String, String> headers = new HashMap<>();
        oldHeaders.forEach((key,value) -> {
            try {
                headers.put(key, URLEncoder.encode(value,"UTF-8"));
            } catch (UnsupportedEncodingException e) {
                throw new RuntimeException(e);
            }
        });
```
正如你看到的那样，在将Authorization放入header的时候会进行encode这会造成JWT产生的token被转移而造成token无效的问题

**Comment by HK-hub** [comment]
我有几个建议改进的地方

1.可以在@HeaderPar里面增加encoded属性，表示是否已经进行了编码，如果true则后续不需要编码了，直接放入headerMap中即可
```java
@Target({ElementType.FIELD, ElementType.ANNOTATION_TYPE,ElementType.PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface HeaderPar {

    /**
     *  Request header name
     */
    String value() default "";
   // 表示是否已经编码：true:已经编码，后续直接放入，不用再编码
    boolean encoded() default false;
}
```

2.将HttpSender 变为Bean，支持用户自定义HttpSender注入进入Spring ，以达到覆盖原有sendHttpRequest()的逻辑

3.HttpApiProcessor 生命周期处理器钩子函数粒度太粗。
```java
default HttpResponse<?> postSendingHttpRequest(HttpSender httpSender, HttpMetadata httpMetadata, HttpApiMethodInvocation<T> methodInvocation){
        return httpSender.sendHttpRequest(httpMetadata);
    }
```
postSendingHttpRequest方法直接调用sendHttpRequest不能在这里面最后再次调整请求header等。建议将sendHttpRequest()方法逻辑里面的request请求构建部分分离作为单独的生命周期：一个构建的过程成为postBuildHttpRequest()方法。里面进行请求的构建过程

**Comment by burukeYou** [comment]
> 对接第三方接口使用JWT作为token发送会被HttpSender里面的URL.encode()转义造成token无效问题 com.burukeyou.uniapi.http.core.channel.DefaultHttpApiInvoker#sendHttpRequest
> 
> ```java
> Map<String, String> headers = new HashMap<>();
>         oldHeaders.forEach((key,value) -> {
>             try {
>                 headers.put(key, URLEncoder.encode(value,"UTF-8"));
>             } catch (UnsupportedEncodingException e) {
>                 throw new RuntimeException(e);
>             }
>         });
> ```
> 
> 正如你看到的那样，在将Authorization放入header的时候会进行encode这会造成JWT产生的token被转移而造成token无效的问题



> ```java
> URLEncoder.encode(value,"UTF-8")
> ```



> 对接第三方接口使用JWT作为token发送会被HttpSender里面的URL.encode()转义造成token无效问题 com.burukeyou.uniapi.http.core.channel.DefaultHttpApiInvoker#sendHttpRequest
> 
> ```java
> Map<String, String> headers = new HashMap<>();
>         oldHeaders.forEach((key,value) -> {
>             try {
>                 headers.put(key, URLEncoder.encode(value,"UTF-8"));
>             } catch (UnsupportedEncodingException e) {
>                 throw new RuntimeException(e);
>             }
>         });
> ```
> 
> 正如你看到的那样，在将Authorization放入header的时候会进行encode这会造成JWT产生的token被转移而造成token无效的问题

被转移是什么意思，就是encode前后值不一样了吗， 好像有中文才会encode前后不一样。 但是如果有中文直接放到header里是会发送不了Http请求的，会抛异常

**Comment by burukeYou** [comment]
> 我有几个建议改进的地方
> 
> 1.可以在@HeaderPar里面增加encoded属性，表示是否已经进行了编码，如果true则后续不需要编码了，直接放入headerMap中即可
> 
> ```java
> @Target({ElementType.FIELD, ElementType.ANNOTATION_TYPE,ElementType.PARAMETER})
> @Retention(RetentionPolicy.RUNTIME)
> @Documented
> public @interface HeaderPar {
> 
>     /**
>      *  Request header name
>      */
>     String value() default "";
>    // 表示是否已经编码：true:已经编码，后续直接放入，不用再编码
>     boolean encoded() default false;
> }
> ```
> 
> 2.将HttpSender 变为Bean，支持用户自定义HttpSender注入进入Spring ，以达到覆盖原有sendHttpRequest()的逻辑
> 
> 3.HttpApiProcessor 生命周期处理器钩子函数粒度太粗。
> 
> ```java
> default HttpResponse<?> postSendingHttpRequest(HttpSender httpSender, HttpMetadata httpMetadata, HttpApiMethodInvocation<T> methodInvocation){
>         return httpSender.sendHttpRequest(httpMetadata);
>     }
> ```
> 
> postSendingHttpRequest方法直接调用sendHttpRequest不能在这里面最后再次调整请求header等。建议将sendHttpRequest()方法逻辑里面的request请求构建部分分离作为单独的生命周期：一个构建的过程成为postBuildHttpRequest()方法。里面进行请求的构建过程

1、第一点要不直接去掉不encode了？， 我加endoe是为了防止有中文和一些特殊字符的请求头， 但是好像基本很少这种场景
2、第二点就先不弄成bean，目前要覆盖或者重写的话可以直接实现HttpApiProcessor.postSendingHttpRequest扩展点， 后面支持做多http客户端比如httpClient、Okhttp再看怎么兼容适配。
3、第三点确实比较粗，先列了几个必备的扩展点，后续再根据实际需求场景慢慢增加扩展点。 
 至于要调整请求header和构建参数之类， 可以在HttpApiProcessor.postBeforeHttpMetadata 自定义怎么构建请求参数（里面可以拿到方法调用的所有信息）， 这个扩展点就是你说的postBuildHttpRequest请求参数构建吧已经有了

**Comment by HK-hub** [comment]
> > 对接第三方接口使用JWT作为token发送会被HttpSender里面的URL.encode()转义造成token无效问题 com.burukeyou.uniapi.http.core.channel.DefaultHttpApiInvoker#sendHttpRequest
> > 
> > ```java
> > Map<String, String> headers = new HashMap<>();
> >         oldHeaders.forEach((key,value) -> {
> >             try {
> >                 headers.put(key, URLEncoder.encode(value,"UTF-8"));
> >             } catch (UnsupportedEncodingException e) {
> >                 throw new RuntimeException(e);
> >             }
> >         });
> > ```
> > 
> > 正如你看到的那样，在将Authorization放入header的时候会进行encode这会造成JWT产生的token被转移而造成token无效的问题
> 
> 
> 
> > ```java
> > URLEncoder.encode(value,"UTF-8")
> > ```
> 
> 
> 
> > 对接第三方接口使用JWT作为token发送会被HttpSender里面的URL.encode()转义造成token无效问题 com.burukeyou.uniapi.http.core.channel.DefaultHttpApiInvoker#sendHttpRequest
> > 
> > ```java
> > Map<String, String> headers = new HashMap<>();
> >         oldHeaders.forEach((key,value) -> {
> >             try {
> >                 headers.put(key, URLEncoder.encode(value,"UTF-8"));
> >             } catch (UnsupportedEncodingException e) {
> >                 throw new RuntimeException(e);
> >             }
> >         });
> > ```
> > 
> > 正如你看到的那样，在将Authorization放入header的时候会进行encode这会造成JWT产生的token被转移而造成token无效的问题
> 
> 被转移是什么意思，就是encode前后值不一样了吗， 好像有中文才会encode前后不一样。 但是如果有中文直接放到header里是会发送不了Http请求的，会抛异常

不是，encode还会对特殊字符进行转义啊，JWT里面有＝等会被转义

**Comment by HK-hub** [comment]
> > 我有几个建议改进的地方
> > 
> > 1.可以在@HeaderPar里面增加encoded属性，表示是否已经进行了编码，如果true则后续不需要编码了，直接放入headerMap中即可
> > 
> > ```java
> > @Target({ElementType.FIELD, ElementType.ANNOTATION_TYPE,ElementType.PARAMETER})
> > @Retention(RetentionPolicy.RUNTIME)
> > @Documented
> > public @interface HeaderPar {
> > 
> >     /**
> >      *  Request header name
> >      */
> >     String value() default "";
> >    // 表示是否已经编码：true:已经编码，后续直接放入，不用再编码
> >     boolean encoded() default false;
> > }
> > ```
> > 
> > 2.将HttpSender 变为Bean，支持用户自定义HttpSender注入进入Spring ，以达到覆盖原有sendHttpRequest()的逻辑
> > 
> > 3.HttpApiProcessor 生命周期处理器钩子函数粒度太粗。
> > 
> > ```java
> > default HttpResponse<?> postSendingHttpRequest(HttpSender httpSender, HttpMetadata httpMetadata, HttpApiMethodInvocation<T> methodInvocation){
> >         return httpSender.sendHttpRequest(httpMetadata);
> >     }
> > ```
> > 
> > postSendingHttpRequest方法直接调用sendHttpRequest不能在这里面最后再次调整请求header等。建议将sendHttpRequest()方法逻辑里面的request请求构建部分分离作为单独的生命周期：一个构建的过程成为postBuildHttpRequest()方法。里面进行请求的构建过程
> 
> 1、第一点要不直接去掉不encode了？， 我加endoe是为了防止有中文和一些特殊字符的请求头， 但是好像基本很少这种场景
> 2、第二点就先不弄成bean，目前要覆盖或者重写的话可以直接实现HttpApiProcessor.postSendingHttpRequest扩展点效果是一样的， 后面支持做多http客户端比如httpClient、Okhttp再看怎么兼容适配。
> 3、第三点确实比较粗，先列了几个必备的扩展点，后续再根据实际需求场景慢慢增加扩展点。 
>  至于要调整请求header和构建参数之类， 可以在HttpApiProcessor.postBeforeHttpMetadata 自定义怎么构建请求参数（里面可以拿到方法调用的所有信息）， 这个扩展点就是你说的postBuildHttpRequest请求参数构建吧已经有了

但问题是 ，即使你在postBeforeHttpMetadata中进行了设置请求头，但是你的发送方法是直接写死的会encode呢，并且如果需要改造你的send方法其实改动还挺麻烦的，需要处理不需要的逻辑

**Comment by HK-hub** [comment]
至于你的encode可以不用取消，可以在@HttpApi注解中添加autoencode 属性来控制是否自动编码，然后每个header par中单独控制请求头编码即可呢

**Comment by burukeYou** [comment]
我先去掉了，对用户传递值进行编码改变值确实不太好， 编码这种东西感觉是一个模块后面再看怎么设计
