### ISSUE TITLE
想记录请求日志，如何获取请求耗时？

### ISSUE THREAD

**Issue by kokolijk** [burukeYou/UniAPI#12]
项记录请求日志，在Processor中可以取到HttpMetadata和response，但是如何获取请求耗时？

**Comment by burukeYou** [comment]
重写 postSendingHttpRequest方法，自己计算耗时
比如
    default HttpResponse<?> postSendingHttpRequest(HttpSender httpSender, HttpMetadata httpMetadata, HttpApiMethodInvocation<T> methodInvocation){
        StopWatch stopWatch = new StopWatch();
        stopWatch.start();
        return httpSender.sendHttpRequest(httpMetadata);
        stopWatch.stop();
    }

**Comment by burukeYou** [comment]
重写 postSendingHttpRequest方法，自己计算耗时
比如
    default HttpResponse<?> postSendingHttpRequest(HttpSender httpSender, HttpMetadata httpMetadata, HttpApiMethodInvocation<T> methodInvocation){
        StopWatch stopWatch = new StopWatch();
        stopWatch.start();
        return httpSender.sendHttpRequest(httpMetadata);
        stopWatch.stop();
    }

**Comment by kokolijk** [comment]
多谢
