### ISSUE TITLE
请求第三方接口时报错

### ISSUE THREAD

**Issue by aches** [burukeYou/UniAPI#13]
com.burukeyou.uniapi.http.core.exception.SendHttpRequestException: Http请求网络IO异常

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/3a57e47f-c1c7-4862-aaa8-e98ff1c5910e">

**Comment by burukeYou** [comment]
是不是要SSL认证，你自定义Okhttp客户端去配一下

**Comment by aches** [comment]
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/78e0622b-5478-4635-9f92-d17a15c3accd">
<img width="776" alt="image" src="https://github.com/user-attachments/assets/8a0fc4e7-4636-4ffc-9adc-031e56e7e29c">
这个接口正常浏览器都是可以访问的,不需要ssl认证,我以为是tls版本的问题,调整过后还是不行

**Comment by aches** [comment]
> 是不是要SSL认证，你自定义Okhttp客户端去配一下

试了一下用hutool的网络请求没问题.
<img width="580" alt="image" src="https://github.com/user-attachments/assets/f2f50835-4536-471d-8e4d-c76596b85a93">


请求的是这个域名 ,可以试一下 https://marketing-api.vivo.com.cn

**Comment by burukeYou** [comment]
> > 是不是要SSL认证，你自定义Okhttp客户端去配一下
> 
> 试了一下用hutool的网络请求没问题. <img alt="image" width="580" src="https://private-user-images.githubusercontent.com/6263299/385344271-f2f50835-4536-471d-8e4d-c76596b85a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDE0MTYsIm5iZiI6MTczMTUwMTExNiwicGF0aCI6Ii82MjYzMjk5LzM4NTM0NDI3MS1mMmY1MDgzNS00NTM2LTQ3MWQtOGU0ZC1jNzY1OTZiODVhOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMTIzMTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ3NWI0YWMxNmM1OGY0Nzk0ZDgzNGQzODNkN2RiNTEzMWY2ODIxOTE3NjNlMzY4Y2UwMjY1NDFmNTc3YjI5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hK24upVjxYtbXYRVnO9oj2Qi1E9dIgyyV5jzx_E6_qg">
> 
> 请求的是这个域名 ,可以试一下 https://marketing-api.vivo.com.cn

那你直接手动用OkhttpClient去请求会不会

**Comment by burukeYou** [comment]
ssl配置问题， 0.2.0新增ssl配置。  hutool默认是无脑信任所有证书的所以没问题
