### ISSUE TITLE
如何取消重定向

### ISSUE THREAD

**Issue by m839336369** [burukeYou/UniAPI#3]
如何取消重定向

**Comment by burukeYou** [comment]
不太理解你的问题，可以详细描述一下吗

**Comment by burukeYou** [comment]
好像是Http客户端的默认行为，自定义okhttp客户端，然后关闭掉重定向试试？

**Comment by m839336369** [comment]
> 好像是Http客户端的默认行为，自定义okhttp客户端，然后关闭掉重定向试试？

好的，已经解决，非常感谢。
