### ISSUE TITLE
注解问题

### ISSUE THREAD

**Issue by 1790818487** [burukeYou/UniAPI#5]
@Configuration
public class TestConfig implements HttpApiProcessor<HttpApi> {无效，有时候注解感觉失效了，想打印原始数据看下，发现这个类也没有作用

**Comment by 1790818487** [comment]
@Configuration
public class TestConfig implements HttpApiProcessor<HttpApi> {主要就是想实现这一个查看这个注解下的时候，我也试了试源码给的测试发现是可以的，就是这个不可以了，也没空看，先提一个issues，而且经常遇到注解无效的问题，基本排查不了，时间来不及，只能换其他麻烦点的请求方式

**Comment by 1790818487** [comment]
`public class TestConfig implements HttpApiProcessor<HttpApi> {`

**Comment by burukeYou** [comment]
你得用 @Component  注解将TestConfig 注入Spring 而不是 @configuration 吧

**Comment by 1790818487** [comment]
这两个都试过了，确实没有用

**Comment by burukeYou** [comment]
> 这两个都试过了，确实没有用

要排查下Spring是否确定扫描到了这个TestConfig ， 然后还要指定到具体的HttpApi注解上. 
 类似: @HttpApi(processor = TestConfig .class,
interface UserAPI {
   
}
这样UserAPI 走接口调用时才会执行到 TestConfig  的扩展点
