### ISSUE TITLE
连接未正确关闭

### ISSUE THREAD

**Issue by 1790818487** [burukeYou/UniAPI#8]
WARN okhttp3.OkHttpClient - A connection to http://host:port was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by 1790818487** [comment]
循环连接的时候就会出现，一般出现在响应体的string方法，这个无法自动关闭响应体

**Comment by 1790818487** [comment]
https://github.com/square/okhttp/issues/2311

**Comment by burukeYou** [comment]
ok我看看，下午发版

**Comment by 1790818487** [comment]
不是这个导致的，可以不用排查了

**Comment by burukeYou** [comment]
> 不是这个导致的，可以不用排查了

那是啥导致的
